"""
DOCX design report generator using python-docx. Renders from the shared
ReportData structure (report_data.py) so its numbers always match the
other formats for the same design/analysis run.
"""
from __future__ import annotations
import io

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.reporting.report_data import ReportData

ACCENT = RGBColor(0x25, 0x63, 0xEB)


def _heading(doc: Document, text: str, level: int = 1):
    doc.add_heading(text, level=level)


def _kv_table(doc: Document, rows: list[tuple[str, str]]):
    table = doc.add_table(rows=0, cols=2)
    table.style = "Light Grid Accent 1"
    for k, v in rows:
        row = table.add_row().cells
        row[0].text = k
        row[1].text = v
    return table


def generate_docx_report(data: ReportData) -> bytes:
    doc = Document()

    title = doc.add_heading(f"Hybrid VAWT Design Report — {data.geometry.name}", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(
        f"Target: {data.geometry.target_power_w:.0f} W  |  "
        f"Material: {data.material_key}  |  "
        f"Operating point: {data.wind_speed_ms:.1f} m/s, TSR {data.operating_tsr:.2f}"
    )
    run.italic = True

    _heading(doc, "1. Executive Summary", 1)
    doc.add_paragraph(
        f"This report summarises the aerodynamic, structural, composite, fatigue, "
        f"aeroelastic, and economic analysis of a {data.geometry.target_power_w:.0f} W "
        f"hybrid Darrieus-Savonius vertical axis wind turbine, generated by the platform's "
        f"own analysis pipeline (Stages 1 through 8). All figures below come from a single "
        f"analysis run, so results are internally consistent across sections."
    )
    _kv_table(doc, [
        ("Peak power coefficient (Cp)", f"{data.peak_cp:.3f} at TSR {data.peak_cp_tsr:.2f}"),
        ("Structural safety factor", f"{data.structural_safety_factor:.2f}"),
        ("Estimated fatigue life", f"{data.fatigue_life_years:,.0f} years" if data.fatigue_life_years < 1e6 else "1,000,000+ years"),
        ("Annual Energy Production (AEP)", f"{data.aep_kwh:,.0f} kWh/yr"),
        ("Levelized Cost of Energy (LCOE)", f"${data.lcoe_usd_per_kwh:.3f}/kWh"),
        ("Net Present Value (20-yr)", f"${data.npv_usd:,.0f}"),
    ])

    _heading(doc, "2. Geometry", 1)
    d, s = data.geometry.darrieus, data.geometry.savonius
    _kv_table(doc, [
        ("Darrieus blades", str(d.num_blades)),
        ("Rotor radius", f"{d.rotor_radius_m:.3f} m"),
        ("Blade height", f"{d.blade_height_m:.3f} m"),
        ("Chord", f"{d.chord_m:.3f} m"),
        ("Airfoil", d.airfoil),
        ("Solidity", f"{d.solidity:.3f}"),
        ("Savonius buckets", str(s.num_buckets)),
        ("Savonius bucket diameter", f"{s.bucket_diameter_m:.3f} m"),
    ])

    _heading(doc, "3. Aerodynamics (Stage 1 — BEM)", 1)
    doc.add_paragraph(
        "Aerodynamic performance is computed via a single-streamtube momentum model "
        "(Templin, 1974) for the Darrieus stage, coupled with an empirical Cp-lambda "
        "correlation for the Savonius stage. The induction factor is solved iteratively "
        f"to balance blade-element and momentum-theory thrust. Peak system Cp of "
        f"{data.peak_cp:.3f} occurs at a tip-speed ratio of {data.peak_cp_tsr:.2f}, well "
        f"below the Betz limit of 0.593, as required by momentum theory."
    )

    _heading(doc, "4. Structural Analysis (Stage 3 — FEA)", 1)
    doc.add_paragraph(
        "The blade spar is modelled as a hollow rectangular box beam under Euler-Bernoulli "
        "bending theory, solved via a validated finite element method (4 DOF/node cubic "
        "Hermite beam elements), subjected to peak per-revolution aerodynamic loading plus "
        "centrifugal loading at the operating point."
    )
    _kv_table(doc, [
        ("Spar mass", f"{data.spar_mass_kg:.3f} kg"),
        ("Combined max stress", f"{data.structural_max_stress_pa/1e6:.1f} MPa"),
        ("Max flapwise deflection", f"{data.structural_max_deflection_m*1000:.2f} mm"),
        ("Safety factor", f"{data.structural_safety_factor:.2f}"),
    ])

    _heading(doc, "5. Composite Material Comparison (Stage 4 — CLT)", 1)
    doc.add_paragraph(
        "Spar cap and shear web layups are optimised independently via Classical Laminate "
        "Theory for both carbon fibre (CFRP) and glass fibre (GFRP), minimising mass subject "
        "to a 1.5 safety factor target."
    )
    _kv_table(doc, [
        ("CFRP spar mass (feasible)", f"{data.composite_cfrp_mass_kg*1000:.0f} g ({'yes' if data.composite_cfrp_feasible else 'no'})"),
        ("GFRP spar mass (feasible)", f"{data.composite_gfrp_mass_kg*1000:.0f} g ({'yes' if data.composite_gfrp_feasible else 'no'})"),
    ])

    _heading(doc, "6. Fatigue Analysis (Stage 5)", 1)
    doc.add_paragraph(
        "Fatigue life is estimated via rainflow counting of the per-revolution azimuthal "
        "aerodynamic load cycle (the dominant VAWT fatigue driver), combined with a Weibull "
        "wind distribution and Palmgren-Miner cumulative damage summation against a Basquin "
        "S-N curve."
    )
    life_str = f"{data.fatigue_life_years:,.1f} years" if data.fatigue_life_years < 1e6 else "1,000,000+ years (effectively unlimited)"
    _kv_table(doc, [
        ("Estimated fatigue life", life_str),
        ("Cycles per year", f"{data.fatigue_cycles_per_year/1e6:.1f} million"),
    ])

    _heading(doc, "7. Aeroelasticity (Stage 6)", 1)
    doc.add_paragraph(
        "Natural frequencies and mode shapes are computed via a generalised eigenvalue "
        "solve using a consistent mass matrix. Resonance risk is assessed via a Campbell "
        "diagram cross-referenced against the real harmonic content of the Stage-1 "
        "aerodynamic loading (via FFT), rather than assuming 1P is always dominant."
    )
    freqs_str = ", ".join(f"{f:.1f} Hz" for f in data.natural_frequencies_hz)
    _kv_table(doc, [
        ("Natural frequencies (modes 1-4)", freqs_str),
        ("Resonance risks in operating range", str(data.resonance_risks_count)),
    ])

    _heading(doc, "8. Economics (Stage 7)", 1)
    doc.add_paragraph(
        "Annual Energy Production integrates the Stage-1 power curve (rated-power-limited, "
        "with system losses) against a Weibull wind distribution. CAPEX uses the real "
        "Stage-4 composite spar mass for material cost, plus parametric generator/tower/"
        "installation costs. LCOE, NPV, and IRR follow standard discounted cash flow methods."
    )
    _kv_table(doc, [
        ("AEP", f"{data.aep_kwh:,.0f} kWh/yr"),
        ("Capacity factor", f"{data.capacity_factor*100:.1f}%"),
        ("Total CAPEX", f"${data.total_capex_usd:,.0f}"),
        ("LCOE", f"${data.lcoe_usd_per_kwh:.3f}/kWh"),
        ("NPV (20-yr)", f"${data.npv_usd:,.0f}"),
        ("IRR", f"{data.irr*100:.1f}%" if data.irr is not None else "N/A"),
        ("Simple payback", f"{data.payback_years:.1f} years" if data.payback_years != float("inf") else "never"),
    ])

    _heading(doc, "9. Warnings & Assumptions", 1)
    if data.warnings:
        for w in data.warnings:
            doc.add_paragraph(w, style="List Bullet")
    else:
        doc.add_paragraph("No warnings raised for this design.")

    _heading(doc, "10. References", 1)
    refs = [
        "Templin, R.J. (1974). Aerodynamic performance theory for the NRC vertical-axis wind turbine.",
        "Paraschivoiu, I. (2002). Wind Turbine Design: With Emphasis on Darrieus Concept.",
        "Jones, R.M. (1999). Mechanics of Composite Materials, 2nd ed.",
        "ASTM E1049-85 (2017). Standard Practices for Cycle Counting in Fatigue Analysis.",
        "Blevins, R.D. (1979). Formulas for Natural Frequency and Mode Shape.",
        "IEC 61400-2 (2013). Wind turbines — Part 2: Small wind turbines.",
    ]
    for r in refs:
        doc.add_paragraph(r, style="List Bullet")

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()
